export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const GET_POSTS = "GET_POSTS";
export const GET_POST_DETAIL = "GET_POST_DETAIL";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";

export const SEARCH_POSTS = "SEARCH_POSTS";
export const CLEAR_POST_DETAIL = "CLEAR_POST_DETAIL";
export const LIKE = "LIKE";
export const DISLIKE = "DISLIKE";

export const GET_POSTS_FILTERED = "GET_POSTS_FILTERED";
export const SET_POSTS_FILTERS = "SET_POSTS_FILTERS";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";

export const CREATE_POST_REVIEW = "CREATE_POST_REVIEW";
export const DELETE_POST_REVIEW = "CREATE_POST_REVIEW";
export const UPDATE_POST_REVIEW = "UPDATE_POST_REVIEW";

export const GET_POSTS_BY_CATEGORIES = "GET_POSTS_BY_CATEGORIES";
export const GET_POSTS_BY_ONGS = "GET_POSTS_BY_ONGS";
export const GET_POSTS_BY_DATE = "GET_POSTS_BY_DATE";

export const SET_LOADING = 'SET_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SET_ORDERINGS = "SET_ORDERINGS";
export const SET_SELECTED_FILTER_OPTIONS = 'SET_SELECTED_FILTER_OPTIONS'
