export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTION_DETAIL = "GET_QUESTION_DETAIL";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const GET_QUESTIONS_FILTERED = "GET_QUESTIONS_FILTERED";
export const CLEAR_QUESTION_DETAIL = "CLEAR_QUESTION_DETAIL";
export const SET_QUESTIONS_FILTERS = "SET_QUESTIONS_FILTERS";
export const SET_QUESTIONS_ORDERINGS = 'SET_QUESTIONS_ORDERINGS';
export const SET_SELECTED_FILTER_OPTION = 'SET_SELECTED_FILTER_OPTION';
export const SET_SELECTED_ORDERING_OPTION = 'SET_SELECTED_ORDERING_OPTION';

