export const types = {
    REGISTER : 'REGISTER',
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    GET_PROFILE : 'GET_PROFILE',
    ERROR_REGISTER : 'ERROR_REGISTER',
    ERROR_LOGIN : 'ERROR_LOGIN',
    IS_AUTHENTICATED : 'IS_AUTHENTICATED',
    LOGIN_WITH_GOOGLE : 'LOGIN_WITH_GOOGLE',    

}