export const types = {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOGIN_WITH_GOOGLE: 'LOGIN_WITH_GOOGLE',
    GET_PROFILE: 'GET_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    DELETE_PROFILE: 'DELETE_PROFILE',
    ERROR_REGISTER: 'ERROR_REGISTER',
    ERROR_LOGIN: 'ERROR_LOGIN',
    IS_AUTHENTICATED: 'IS_AUTHENTICATED',


}